use indexmap::IndexMap;

/// A single MAF record (one row in the output file).
///
/// Fields follow MAF v2.4 / GDC column order. Extra VEP annotations
/// are stored in `extra` and appended after the standard columns.
#[derive(Debug, Default, Clone)]
pub struct MafRecord {
    pub hugo_symbol: String,
    pub entrez_gene_id: String,
    pub center: String,
    pub ncbi_build: String,
    pub chromosome: String,
    pub start_position: u64,
    pub end_position: u64,
    pub strand: String,
    pub variant_classification: String,
    pub variant_type: String,
    pub reference_allele: String,
    pub tumor_seq_allele1: String,
    pub tumor_seq_allele2: String,
    pub dbsnp_rs: String,
    pub dbsnp_val_status: String,
    pub tumor_sample_barcode: String,
    pub matched_norm_sample_barcode: String,
    pub match_norm_seq_allele1: String,
    pub match_norm_seq_allele2: String,
    pub tumor_validation_allele1: String,
    pub tumor_validation_allele2: String,
    pub match_norm_validation_allele1: String,
    pub match_norm_validation_allele2: String,
    pub verification_status: String,
    pub validation_status: String,
    pub mutation_status: String,
    pub sequencing_phase: String,
    pub sequence_source: String,
    pub validation_method: String,
    pub score: String,
    pub bam_file: String,
    pub sequencer: String,
    pub tumor_sample_uuid: String,
    pub matched_norm_sample_uuid: String,
    pub hgvsc: String,
    pub hgvsp: String,
    pub hgvsp_short: String,
    pub transcript_id: String,
    pub exon_number: String,
    pub t_depth: String,
    pub t_ref_count: String,
    pub t_alt_count: String,
    pub n_depth: String,
    pub n_ref_count: String,
    pub n_alt_count: String,
    pub all_effects: String,
    // VEP passthrough fields
    pub vep_allele: String,
    pub vep_gene: String,
    pub vep_feature: String,
    pub vep_biotype: String,
    pub vep_canonical: String,
    pub vep_sift: String,
    pub vep_polyphen: String,
    /// Extra retained VEP annotation fields (--retain-ann)
    pub extra: IndexMap<String, String>,
}

pub const STANDARD_COLUMNS: &[&str] = &[
    "Hugo_Symbol",
    "Entrez_Gene_Id",
    "Center",
    "NCBI_Build",
    "Chromosome",
    "Start_Position",
    "End_Position",
    "Strand",
    "Variant_Classification",
    "Variant_Type",
    "Reference_Allele",
    "Tumor_Seq_Allele1",
    "Tumor_Seq_Allele2",
    "dbSNP_RS",
    "dbSNP_Val_Status",
    "Tumor_Sample_Barcode",
    "Matched_Norm_Sample_Barcode",
    "Match_Norm_Seq_Allele1",
    "Match_Norm_Seq_Allele2",
    "Tumor_Validation_Allele1",
    "Tumor_Validation_Allele2",
    "Match_Norm_Validation_Allele1",
    "Match_Norm_Validation_Allele2",
    "Verification_Status",
    "Validation_Status",
    "Mutation_Status",
    "Sequencing_Phase",
    "Sequence_Source",
    "Validation_Method",
    "Score",
    "BAM_File",
    "Sequencer",
    "Tumor_Sample_UUID",
    "Matched_Norm_Sample_UUID",
    "HGVSc",
    "HGVSp",
    "HGVSp_Short",
    "Transcript_ID",
    "Exon_Number",
    "t_depth",
    "t_ref_count",
    "t_alt_count",
    "n_depth",
    "n_ref_count",
    "n_alt_count",
    "all_effects",
    "Allele",
    "Gene",
    "Feature",
    "BIOTYPE",
    "CANONICAL",
    "SIFT",
    "PolyPhen",
];

